src/blog/blog/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from accounts.views import (
    login_view,
    register_view,
    logout_view,
)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^posts/', include("posts.urls", namespace='posts')),
    url(r'^comments/', include("comments.urls", namespace='comments')),
    url(r'^login/', login_view, name='login'),
    url(r'^logout/', logout_view, name='logout'),
    url(r'^register/', register_view, name='register'),
    url(r'^api/posts/', include("posts.api.urls", namespace="posts-api")),
    url(r'^api/comments/', include("comments.api.urls", namespace="comments-api")),
    url(r'^api/users/', include("accounts.api.urls", namespace="users-api"))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/blog/posts/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.post_list, name="home"),
    url(r'^create/$', views.post_create, name='create'),
    url(r'^(?P<slug>[\w-]+)/$', views.post_detail, name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', views.post_update, name='update'),
    url(r'^(?P<slug>[\w-]+)/delete/$', views.post_delete),
    ]

src/blog/posts/models.py
from __future__ import unicode_literals
from django.conf import settings
from django.db import models
from django.contrib.contenttypes.models import ContentType
from django.core.urlresolvers import reverse
from django.db.models.signals import pre_save
from django.utils import timezone
from django.utils.safestring import mark_safe
from django.utils.text import slugify
from markdown_deux import markdown
from comments.models import Comment
from .utils import get_read_time

# Create your models here.


class PostManager(models.Manager):
    def active(self, *args, **kwargs):
        return super(PostManager, self).filter(draft=False).filter(publish__lte=timezone.now())


def upload_location(instance, filename):
    return "%s/%s" %(instance.slug, filename)


class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
    title = models.CharField(max_length=120)
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to=upload_location,
                              null=True,
                              blank=True,
                              height_field="height_field",
                              width_field="width_field")
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    content = models.TextField()
    draft = models.BooleanField(default=False)
    publish = models.DateField(auto_now=False, auto_now_add=False)
    read_time = models.IntegerField(default=0)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

    objects = PostManager()

    def get_absolute_url(self):
        return reverse("posts:detail", kwargs={"slug": self.slug})
        # return "/posts/%s/" %(self.id)

    def get_api_url(self):
        return reverse("posts-api:detail", kwargs={"slug": self.slug})

    def __unicode__(self):
        return self.title

    class Meta:
        ordering = ["-timestamp", "-updated"]

    def get_markdown(self):
        content = self.content
        return mark_safe(markdown(content))

    @property
    def comments(self):
        instance = self
        qs = Comment.objects.filter_by_instance(instance)
        return qs

    @property
    def get_content_type(self):
        instance = self
        content_type = ContentType.objects.get_for_model(instance.__class__)
        return content_type


def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Post.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" %(slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)
    if instance.content:
        html_string = instance.get_markdown()
        read_time = get_read_time(html_string)
        instance.read_time = read_time


pre_save.connect(pre_save_post_receiver, sender=Post)

src/blog/posts/forms.py
from django import forms
from .models import Post
from pagedown.widgets import PagedownWidget


class PostForm(forms.ModelForm):
    publish = forms.DateField(widget=forms.SelectDateWidget)
    content = forms.CharField(widget=PagedownWidget(show_preview=False))

    class Meta:
        model = Post
        fields = [
            "title",
            "image",
            "content",
            "draft",
            "publish",
        ]

src/blog/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet"
              href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
              integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
              crossorigin="anonymous">

        <!-- Optional theme -->
        <link rel="stylesheet"
              href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
              integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp"
              crossorigin="anonymous">
        {% block head_extra %}{% endblock head_extra %}
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
        <title>{% block title %}Mama's Blog{% endblock title%}</title>
    </head>

    <body>
        <div id="fb-root"></div>
        <script>(function(d, s, id) {
                  var js, fjs = d.getElementsByTagName(s)[0];
                  if (d.getElementById(id)) return;
                  js = d.createElement(s); js.id = id;
                  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.10";
                  fjs.parentNode.insertBefore(js, fjs);
                }(document, 'script', 'facebook-jssdk'));</script>

        {% block content%}
        {% endblock content %}

        <script
			  src="http://code.jquery.com/jquery-1.12.4.min.js"
			  integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ="
			  crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.5/marked.min.js"></script>
        <script>
            $(document).ready(function(){
                $(".content-markdown").each(function(){
                    var content = $(this).text()
                    var markedContent = marked(content)
                    $(this).html(markedContent)
                })
                $(".post-detail-item img").each(function(){
                    $(this).addClass("img-responsive");
                })

                var contentInput = $("#id_content");
                function setContent(value){
                    var markedContent = marked(value)
                    $("#preview-content").html(markedContent)
                    $("#preview-content img").each(function(){
                        $(this).addClass("img-responsive")
                    })
                }
                setContent(contentInput.val())
                contentInput.keyup(function(){
                    var newContent = $(this).val()
                    setContent(newContent)
                })
                var titleInput = $("#id_title");

                function setTitle(value) {
                    $("#preview-title").text(value)
                }
                setTitle(titleInput.val())
                titleInput.keyup(function(){
                    var newContent = $(this).val()
                    setTitle(newContent)
                })

                $(".comment-reply-btn").click(function(event) {
                    event.preventDefault();
                    $(this).parent().parent().next(".comment-reply").fadeToggle();
                })
            });
        </script>
    </body>
</html>

src/blog/templates/comment_thread.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Comments{% endblock title %}

{% block content%}
    {% include 'snippets/messages.html' %}
    {% include 'snippets/nav.html' %}

    <section>
        <div class="container">
            <div class="col-sm-6 col-sm-offset-3">
                <div>
                        <h3>{{ comment.user.username }}</h3>
                        <p>{{ comment.content }}</p>
                        <p>
                            <small>{{ comment.timestamp }} |
                                {% if comment.children.count > 0 %}
                                {{ comment.children.count }} Comments
                                {% endif %}
                                {% if request.user == comment.user %}
                                    <a href="delete" class="btn btn-danger">Delete</a>
                                {% endif %}
                            </small>
                        </p>
                        <hr>
                        <div>
                            {% for child_comment in comment.children %}
                            <blockquote>
                                <h3>{{ child_comment.user.username }}</h3>
                                <p>{{ child_comment.content }}</p>
                                <p>
                                    <small>{{ child_comment.timestamp }}</small>
                                    {% if request.user == child_comment.user %}
                                        <a href="delete" class="btn btn-danger">Delete</a>
                                    {% endif %}
                                </p>
                            </blockquote>
                            {% endfor %}
                            {% if request.user.is_authenticated %}
                            <form action="." method="POST">{% csrf_token %}
                                {{ form|crispy }}
                                <input type="hidden" name="parent_id" value="{{ comment.id }}">
                                <input type="submit" value="Reply" class="btn btn-success">
                            </form>
                            {% else %}
                            <p>You must log in to comment</p>
                            {% endif %}
                        </div>
                    <hr>
                </div>
            </div>
        </div>
    </section>

{% endblock content %}

src/blog/templates/confirm_delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Delete Comment{% endblock title %}

{% block content%}
    {% include 'snippets/messages.html' %}
    {% include 'snippets/nav.html' %}

    <section>
        <div class="container">
            <div class="col-sm-6 col-sm-offset-3">
                <h1>Confirm comment deletion</h1>
                <form action="." method="POST">{% csrf_token %}
                    <p>Are you ure you want to delete this comment?</p>
                    <p>"{{ object.content }}"</p>
                    <input type="submit" value="Confirm" class="btn btn-danger">
                    <a href='{{ object.get_absolute_url }}' class="btn btn-warning">
                        I change my mind
                    </a>
                </form>
                <hr>
            </div>
        </div>
    </section>

{% endblock content %}

src/blog/templates/form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}{{ title }}{% endblock title %}

{% block content %}
    {% include 'snippets/nav.html' %}
    <div class="col-sm-6 col-sm-offset-3">
        <h1>{{ title }}</h1>
        <form method="POST" action='' enctype="multipart/form-data">{% csrf_token %}
            {{ form|crispy }}
            <input class="btn btn-success" type="submit" value="{{ title }}">
        </form>
    </div>
{% endblock content %}

src/blog/templates/post_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block head_extra %}{{ form.media }}{% endblock head_extra %}
{% block title %}Create Post{% endblock title %}

{% block content %}
    {% include 'snippets/nav.html' %}
    <div class="col-sm-6">
        <form method="POST" action='' enctype="multipart/form-data">{% csrf_token %}
            {{ form|crispy }}
            <input class="btn btn-success" type="submit" value="Submit Post">
        </form>
    </div>
    <div class="col-sm-6">
        <h1>Preview</h1>
        <div class="content-preview">
            <h3 id="preview-title"></h3>
            <p id="preview-content"></p>
        </div>
    </div>
{% endblock content %}

src/blog/templates/post_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}{{instance.title}}{% endblock title %}

{% block content%}
    {% include 'snippets/messages.html' %}
    {% include 'snippets/nav.html' %}
    <section>
        <div class="container">
            <div class="col-sm-6 col-sm-offset-3">
                {% if instance.image %}
                    <img src="{{ instance.image.url }}" alt="" class="img-resp"/>
                {% endif %}
                <h1>{{ instance.title }}&nbsp;
                    <small>
                        <a href="edit">Update</a>
                    </small>
                </h1>
                {% if instance.user.get_full_name %}
                    <h3>Author: {{ instance.user.get_full_name }}</h3>
                {% else %}
                    <h3>Author: {{ instance.user }}</h3>
                {% endif %}
                <h4>Read time: {% if instance.read_time <= 1 %}
                                     < 1 minute
                                {% else %}{{ instance.read_time }} minutes
                                {% endif %}
                </h4>
                <div class="row">
                    <div class="col-sm-12 post-detail-item">{{ instance.get_markdown }}</div>
                </div>
                <p>
                    <small>Updated: {{ instance.updated }}</small>
                </p>
                <p>
                    {% if instance.draft %}
                        <span class="text-danger">Draft</span>
                    {% endif %}
                    <small>
                        Created: {{ instance.publish }}
                    </small>
                </p>
                <div class="fb-like" data-href="{{ request.build_absolute_url }}" data-layout="standard" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div>
                <p>
                    <a class="btn btn-primary" href="#">Share on FaceBook</a>
                    <a class="btn btn-info" href="#">Share on Twitter</a>
                    <a class="btn btn-danger" href="#">Share on Pinterest</a>
                    <a class="btn btn-warning" href="#">Share on Reddit</a>
                </p>
                <h3 ><a class="text-danger" href="delete">Delete</a></h3>

                <div id="comment">
                    <h2>Comments</h2>
                    {% if request.user.is_authenticated %}
                    <form action="." method="POST">{% csrf_token %}
                        {{ comment_form|crispy }}
                        <input type="submit" value="Post comment" class="btn btn-success">
                    </form>
                    {% else %}
                    <p>You must log in to comment</p>
                    {% endif %}
                    <hr>
                    {% for comment in comments %}
                        <div>
                            <blockquote>
                                <h3>{{ comment.user.username }}</h3>
                                <p>{{ comment.content }}</p>
                                <p>
                                    <small>{{ comment.timestamp }} |
                                        {% if comment.children.count > 0 %}
                                            {{ comment.children.count }} Comments |
                                        {% endif %}
                                        <a class="comment-reply-btn" href="#">Reply</a>
                                        <a href="{{ comment.get_absolute_url }}">Thread</a>
                                        {% if request.user == comment.user %}
                                            <a href="/comments/{{ comment.id }}/delete">Delete</a>
                                        {% endif %}
                                    </small>
                                </p>
                                <div class="comment-reply">
                                    {% for child_comment in comment.children %}
                                        <blockquote>
                                            <h3>{{ child_comment.user.username }}</h3>
                                            <p>{{ child_comment.content }}</p>
                                            <p>
                                                <small>{{ child_comment.timestamp }}</small>
                                            </p>
                                        </blockquote>
                                    {% endfor %}
                                    {% if request.user.is_authenticated %}
                                    <form action="." method="POST">{% csrf_token %}
                                        {{ comment_form|crispy }}
                                        <input type="hidden" name="parent_id" value="{{ comment.id }}">
                                        <input type="submit" value="Reply" class="btn btn-success">

                                    </form>
                                    {% else %}
                                    <p>You must be log in to comment</p>
                                    {% endif %}
                                </div>
                            </blockquote>
                            <hr>
                        </div>

                    {% endfor %}
                </div>
                <!-- <div class="fb-comments" data-href="{{ request.build_absolute_url }}" data-numposts="5"></div> -->
            </div>
        </div>
    </section>

{% endblock content %}

src/blog/templates/post_list.html
{% extends 'base.html' %}
{% block content %}
    {% include 'snippets/navform.html' %}
    <section>
        <div class="container">
            {% if object_list %}
            <div class="col-sm-8 col-sm-offset-2">
                    <div class="row">
                        {% for obj in object_list %}
                            <div class="col-sm-12">
                                <div class="thumbnail">
                                    {% if obj.image %}
                                        <img src="{{ obj.image.url }}" alt="" class="img-resp"/>
                                    {% endif %}
                                    <div class="caption post-detail-item">
                                        <h3>
                                            {% if obj.draft %}
                                                <span class="text-danger">Draft </span>
                                            {% endif %}
                                            {% if obj.publish > today %}
                                                <span class="text-muted">Future Post</span>
                                            {% endif %}
                                        </h3>
                                        <h3><a href='{{ obj.get_absolute_url }}'>
                                            {{ obj.title }}
                                        </a>
                                            {% if obj.user.get_full_name %}
                                                <small>{{ obj.user.get_full_name }}</small>
                                            {% else %}
                                                <small>{{ obj.user }}</small>
                                            {% endif %}
                                        </h3>
                                        {{ obj.get_markdown|truncatewords_html:5 }}
                                        <p>Updated: {{ obj.updated|timesince }} ago</p>
                                        <p>Posted: {{ obj.publish }}</p>
                                        <p>Read time: {% if instance.read_time <= 1 %}
                                                         < 1 minute
                                                        {% else %}{{ instance.read_time }} minutes
                                                    {% endif %}
                                        </p>
                                        <p>
                                            <a class="btn btn-success" href="{{ obj.get_absolute_url }}">View</a>
                                            <a class="btn btn-primary" href="{{ obj.slug }}/edit">Update</a>
                                            <a class="btn btn-danger" href="{% url 'posts:home' %}{{obj.slug}}/delete">Delete</a>
                                        </p>
                                    </div>
                                </div>
                                <hr>
                            </div>
                        <!--{% cycle "" "<div class='col-sm-12'><hr></div></div><div class='row'>" %} -->
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
        </div>
    </section>
    <section>
        <div class="container">
            <div class="pagination">
                <span class="step-links">
                    {% if object_list.has_previous %}
                        <a href="?page={{ contacts.previous_page_number }}
                            {% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">previous</a>
                    {% endif %}

                    <span class="current">
                        Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}
                    </span>

                    {% if object_list.has_next %}
                        <a href="?page={{ object_list.next_page_number }}
                            {% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">next</a>
                    {% endif %}
                </span>
            </div>
        </div>
    </section>
{% endblock content %}

src/blog/templates/post_update.html
{% extends 'base.html' %}

{% block title %}Update Post - {{instance.title}}{% endblock title %}

{% block content %}
{% include 'snippets/nav.html' %}
{% endblock content %}